### ISSUE TITLE
DCDM Inverse ODT

### ISSUE THREAD

**Issue by antonmeleshkevich** [jedypod/open-display-transform#7]
Hi! Here is the example of what I was talking about.
Even with rec709 limited gamut, XYZ image can't be completely used as an input for DCDM. And even if a hard clip the input image far from 0 and 1 values.

I've used Rec709 curve because if I use power law gamma or just Linear, the image that goes into Inverse ODT doesn't contain colors that cause this artifact.

![01](https://user-images.githubusercontent.com/34407001/136286765-2b51a333-7a39-4fda-ab3c-f53f719b80a9.jpg)

![02](https://user-images.githubusercontent.com/34407001/136286768-52788ec1-7117-4f8c-889c-abfd19264aaa.jpg)

![03](https://user-images.githubusercontent.com/34407001/136286769-51a99a3d-175f-4368-8741-6801d9b27346.jpg)

And here is what happens if I replace Inverse ODT and ODT by each other:
![04](https://user-images.githubusercontent.com/34407001/136286770-5ca29066-d673-48d7-8ff2-2a9ef6ee183b.jpg)

**Comment by jedypod** [comment]
Hey again and sorry for the delay in getting back to you about this.

The difference you are seeing there is from the gamut compression, which is applied only in the forward direction. 

This setup is still being prototyped and tested, and I'm leaning towards removing it from the DRT and treating it as an LMT component instead. 

Bigger picture, if you are looking for a display transform with a perfect inverse, OpenDRT is probably not a good fit. Because of the way it is designed there will be more differences in the inverse direction than per-channel approaches like rgbDT or ACES.

I'll close this because the DCDM inverse issue has been resolved, but feel free to report back if you see anything else suspicious! Thanks again for your help and testing.
